Feature/ben/api fhir auth
family-news-feed/python-api pull request #17
Opened 2021-03-04 23:33 UTC by benjamindburke

Create a session cached FHIR connection.

Changes:
- Now you need an entry in your hosts file (on windows this is C:\Windows\System32\drivers\etc\hosts) that reads `local.familynewsfeed.com           127.0.0.1`
- New block of environment variables to configure in scripts\activate.ps1
- Travel to [http://local.familynewsfeed.com:8000/launch/](http://local.familynewsfeed.com:8000/launch/) when running API locally to initiate the FHIR connection. We could consider this our "auth" url, the lambda and other services that need to query DB / FHIR data will need authed first

2021-03-05 01:11 UTC, raymondaing requested changes

2021-03-05 01:11 UTC, raymondaing commented on .vscode/extensions.json
> +{
Don't think this file should be committed.

2021-03-05 01:11 UTC, raymondaing commented on .vscode/settings.json
> +{
Same as above

2021-03-09 01:41 UTC, benjamindburke commented
Merge commits out the wazoo, closing to manually merge all branches in different PR

2021-03-09 01:41 UTC, closed without merging